services:
    php:
        networks:
            - sail
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - storage:/app/storage

    pwa:
        image: ${IMAGES_PREFIX:-}app-pwa
        networks:
            - sail
        environment:
            NEXT_ENTRYPOINT: http://php
            NEXT_PUBLIC_ENTRYPOINT: '${APP_URL}'

networks:
    sail:
        driver: bridge
