# Development environment override
services:
    php:
        build:
            context: './api/vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                MYSQL_CLIENT: mariadb-client
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            APP_ENV: 'local'
            APP_DEBUG: 'true'
        volumes:
            - './api:/var/www/html'
        tty: true
        depends_on:
            - mailpit

    pwa:
        build:
            context: ./pwa
            target: dev
        volumes:
            - ./pwa:/srv/app
        ports:
            - 3000:3000
        environment:
            NEXT_ENTRYPOINT: http://php
            NEXT_PUBLIC_ENTRYPOINT: 'http://localhost'
            # On Linux, you may want to comment the following line for improved performance
            # WATCHPACK_POLLING: "true"

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
