name: Test

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      NEXT_PUBLIC_ENTRYPOINT: http://localhost:8000
      NEXT_ENTRYPOINT: http://localhost:8000
      TELESCOPE_ENABLED: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          ini-values: error_reporting=E_ALL
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        working-directory: api
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        working-directory: api
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Setup app
        working-directory: api
        run: |
          cp .env.example .env
          touch database/database.sqlite
          php artisan key:generate
          php artisan migrate
      - name: Run PHPStan
        working-directory: api
        run: vendor/bin/phpstan --memory-limit=2G --error-format=github
      - name: Run PHPUnit
        working-directory: api
        run: php artisan test
      - name: Run Laravel Server
        working-directory: api
        run: php artisan serve --no-reload --host localhost --port 8888 &
      - name: Check API reachability
        run: curl --fail-with-body http://localhost:8888/up
      - name: Check Docs reachability
        run: curl -vk --fail-with-body http://localhost:8000/docs/api.json
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Cache PNPM
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_HOME }}
          key: ${{ runner.os }}-pnpm-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        working-directory: pwa
        run: pnpm install
      - name: Run ESLint
        working-directory: pwa
        run: pnpm lint
      - name: Migrate and seed database
        working-directory: api
        run: |
          php artisan app:import-movies
          php artisan db:seed
      - name: Run Next.js Server
        working-directory: pwa
        run: pnpm dev &
      - name: Check PWA reachability
        run: curl -vk --fail-with-body http://localhost:3000/movies
      - name: Install Dependencies
        working-directory: e2e
        run: pnpm install
      - name: Cache Playwright Binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
      - name: Install Playwright Browsers with Deps
        working-directory: e2e
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright
        working-directory: e2e
        timeout-minutes: 5
        run: pnpm exec playwright test --workers=1
      - name: Show Laravel logs
        if: failure()
        run: cat api/storage/logs/laravel.log
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: e2e/playwright-report
